src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $signature;

    /**
     * @ORM\Column(type="datetime")
     */
    private $publication_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getSignature(): ?string
    {
        return $this->signature;
    }

    public function setSignature(?string $signature): self
    {
        $this->signature = $signature;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publication_date;
    }

    public function setPublicationDate(\DateTimeInterface $publication_date): self
    {
        $this->publication_date = $publication_date;

        return $this;
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Repository\ArticleRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Form\NewArticleType;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController
{
    /**
     * @Route("/new_article", name="new")
     */
    public function new(Request $request)
    {
        $article = new Article();
        $form = $this->createForm(NewArticleType::class, $article);

        //On récupère les informations du formulaire de création d'un article
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $now = date_create(date('Y-m-d H:i:s'));

            //On complète les informations de l'article manuellement
            $article->setAuthor($this->getUser()->getUsername());
            $article->setPublicationDate($now);

            //On enregistre le nouvel article
	        $em = $this->getDoctrine()->getManager();
	        $em->persist($article);
	        $em->flush();

	        return $this->redirectToRoute('home');
	    }

        return $this->render('article/new.html.twig', [
	        'form'  =>  $form->createView()
	    ]);
    }

    /**
	 * @Route("/article/{id}", name="view")
	 */
    public function view(Article $article){
        if(empty($article)) {
            return $this->render('article/view.html.twig', [
                'article'    =>  ''
            ]);
        }
        else {
            return $this->render('article/view.html.twig', [
                'article'    =>  $article
            ]);
        }        
    }

    
    /**
	 * @Route("/edit/{id}", name="edit")
	 */ 
	public function edit(Article $article, Request $request){
        //Si l'utilisateur connecté correspond à l'auteur de l'article
        if($article->getAuthor() == $this->getUser()->getUsername()) {
            //On lui permet de modifier l'article
            $form = $this->createForm(NewArticleType::class, $article);
            $form->handleRequest($request);
	    
            if($form->isSubmitted() && $form->isValid()){
                $em = $this->getDoctrine()->getManager();
                $em->persist($article);
                $em->flush();

                return $this->redirectToRoute('home');
            }

            return $this->render('article/new.html.twig', [
                'form'  =>  $form->createView()
            ]);
        }
        //Sinon, on le redirige vers l'accueil
        else {
            return $this->redirectToRoute('home');
        }

	    
	}
}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rediger un nouvel article{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Rediger votre nouvel article</h1>

    {{ form_start(form) }}
        {{ form_errors(form) }}
        {{ form_rest(form) }}
        <button type="submit" class="btn btn-primary">Save</button>
	{{ form_end(form) }}
</div>
{% endblock %}

templates/article/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lire un article{% endblock %}

{% block body %}
<div id="content">
    <h1>Bienvenue sur un blog fait avec Symfony 4 ! ✅</h1>
    <hr>
    {% if article is empty %}
        <div id="no-articles">
            <span>Aucun article trouvé</span>
        </div>
    {% else %}
        <h2 class="title-center">{{article.title}}</h2>
        <div class="article col-sm-10">
            {% if app.user.username == article.author %}
                <a href="{{ path('edit', {id: article.id}) }}" title="Editer l'article">
                    <img src="{{ asset('images/edit.png') }}" class="edit-icon"> 
                </a>
            {% endif %}
            <p class="content">{{ article.content }}</p>
            <hr>
            <p class="signature">{{ article.signature }}</p>
            <p class="infos">By<b> {{ article.author}}</b>, {{ article.publicationDate|date('d/m/Y H:i:s')}}</p>
        </div>
    {% endif %}
    <a href="{{ path('home') }}" class="btn btn-info ml-3">
        Retourner à la liste des articles
    </a>
</div>
{% endblock %}